name: Build plugin

on:
  push:

jobs:
  compile_jar:
    runs-on: windows-latest
    
    permissions:
       contents: write
       actions: write
       
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Configure Git User Details
        run: |
          git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

      - name: Apply Patches
        run: ./gradlew clean build
        
      - name: Make release
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "Latest release"
          automatic_release_tag: "latest_plugin"
          files: build/libs/*
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
